language: node_js
node_js:
  - '4'
sudo: false
cache:
  directories:
    - node_modules
before_install:
  - npm config set spin false
  - npm install -g bower
  - npm install -g yarn
  - bower --version
  - npm i phantomjs-prebuilt
  - phantomjs --version
install:
  - yarn
  - bower install

after_success:
  test $TRAVIS_BRANCH = "master" && ember deploy production
script:
  # Usually, it's ok to finish the test scenario without reverting
  #  to the addon's original dependency state, skipping "cleanup".
  - ember try:each --skip-cleanup
