defaults: &defaults
  docker:
    - image: circleci/node:6.12-browsers
      environment:
        JOBS: 2
  working_directory: ~/emberx-select
version: 2.0
references:
  container_config: &container_config
    docker:
      - image: circleci/node:6-browsers
        environment:
          JOBS: 2
    working_directory: ~/emberx-select

  restore_repo: &restore_repo
    restore_cache:
      keys:
        - v1-repo-{{ .Branch }}-{{ .Revision }}
        - v1-repo-{{ .Branch }}
        - v1-repo

  restore_node_modules: &restore_node_modules
    restore_cache:
      keys:
        - v1-dependencies-{{ checksum "package.json" }}
        - v1-dependencies

  restore_bower_components: &restore_bower_components
    restore_cache:
      keys:
        - v1-bower-dependencies-{{ checksum "bower.json" }}
        - v1-bower-dependencies

jobs:
  checkout_code:
    <<: *container_config
    steps:
      - *restore_repo
      - checkout
      - save_cache:
          key: v1-repo-{{ .Branch }}-{{ .Revision }}
          paths:
            - .

  install_dependencies:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *restore_bower_components
      - run: yarn install
      - run: yarn bower-install
      - save_cache:
          key: v1-dependencies-{{ checksum "package.json" }}
          paths:
            - node_modules
      - save_cache:
          key: v1-bower-dependencies-{{ checksum "bower.json" }}
          paths:
            - bower_components

  deploy_master:
      <<: *container_config
      steps:
        - *restore_repo
        - *restore_node_modules
        - *restore_bower_components
        - run:
            name: Deploy Master
            command: yarn deploy

  test-lts-2.12:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *restore_bower_components
      - run: node_modules/.bin/ember try:one ember-lts-2.12 --skip-cleanup

  test-lts-2.16:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *restore_bower_components
      - run: node_modules/.bin/ember try:one ember-lts-2.16 --skip-cleanup

  test-release:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *restore_bower_components
      - run: node_modules/.bin/ember try:one ember-release --skip-cleanup

  test-beta:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *restore_bower_components
      - run: node_modules/.bin/ember try:one ember-beta --skip-cleanup

  test-canary:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *restore_bower_components
      - run: node_modules/.bin/ember try:one ember-canary --skip-cleanup

  test-default:
    <<: *container_config
    steps:
      - *restore_repo
      - *restore_node_modules
      - *restore_bower_components
      - run: node_modules/.bin/ember try:one ember-default --skip-cleanup

workflows:
  version: 2

  build_test:
    jobs:
      - checkout_code

      - install_dependencies:
          requires:
            - checkout_code

      - test-lts-2.12:
          requires:
            - install_dependencies

      - test-lts-2.16:
          requires:
            - install_dependencies

      - test-default:
          requires:
            - install_dependencies

      - test-release:
          requires:
            - install_dependencies

      - test-beta:
          requires:
            - install_dependencies

      - test-canary:
          requires:
            - install_dependencies

      - deploy_master:
          requires:
            - test-lts-2.12
            - test-lts-2.16
            - test-default
            - test-release
            - test-beta
          filters:
            branches:
              only: master
